services:
  - type: web
    name: gympulse-api
    runtime: docker
    repo: https://github.com/Meuxo/gympulse
    dockerfilePath: ./backend/Dockerfile
    rootDir: backend
    envVars:
      - key: MONGODB_URL
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        sync: false
      - key: GOOGLE_PLACES_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: "3.13.0"
      - key: FRONTEND_URL
        sync: false
    plan: free
  - type: web
    name: gympulse-web
    runtime: static
    repo: https://github.com/Meuxo/gympulse
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /api/*
        destination: https://gympulse-api.onrender.com/api/*
      - type: rewrite
        source: /*
        destination: /index.html
    plan: free
